# Generated by Django 2.2.7 on 2019-12-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0002_auto_20191214_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='images',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
