# Generated by Django 2.2.7 on 2019-12-22 05:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0004_auto_20191218_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='boardmodel',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
