# Generated by Django 2.2.7 on 2019-12-29 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
