# Generated by Django 2.2.7 on 2019-12-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0007_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='goodtext',
            field=models.CharField(blank=True, default='a', max_length=100, null=True),
        ),
    ]
